/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_roco_copymedia_CopyJni */

#ifndef _Included_com_roco_copymedia_CopyJni
#define _Included_com_roco_copymedia_CopyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_roco_copymedia_CopyJni
 * Method:    startProcess
 * Signature: (Landroid/content/Context;)V
 */
JNIEXPORT void JNICALL Java_com_roco_copymedia_CopyJni_startProcess
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_roco_copymedia_CopyJni
 * Method:    doSomething
 * Signature: (Ljava/io/File;Ljava/io/File;)V
 */
JNIEXPORT void JNICALL Java_com_roco_copymedia_CopyJni_doSomething
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_roco_copymedia_CopyJni
 * Method:    isCopyDown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_roco_copymedia_CopyJni_isCopyDown
  (JNIEnv *, jclass);

/*
 * Class:     com_roco_copymedia_CopyJni
 * Method:    copyDown
 * Signature: (Landroid/content/Context;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_roco_copymedia_CopyJni_copyDown
  (JNIEnv *, jclass, jobject, jstring);
#ifdef __cplusplus
}
#endif
#endif
